name: Linting, Unit Tests and Doc Checks

on:
  push:
    branches: ["main", "develop"]
    tags: ["v*.*.*"]
  pull_request:
    branches: ["main", "develop"]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 1

      - name: Install uv (official Astral action)
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Set up Python (using uv)
        run: uv python install 3.12

      - name: Install all dependencies
        run: uv sync --all-extras

      - name: Run linting
        run: uv run python devtools/lint.py

      - name: Run tests
        env:
            SPLUNKBASE_USERNAME_FOR_TEST: ${{ secrets.SPLUNKBASE_USERNAME }}
            SPLUNKBASE_PASSWORD_FOR_TEST: ${{ secrets.SPLUNKBASE_PASSWORD }}
        run: uv run pytest --junitxml=junit/test-results.xml --cov=src --cov-config=tests/.coveragerc --cov-report=xml

      - name: Adding GitHub action step summary
        uses: VatsalJagani/pytest-cov-action@v1.4
        with:
          pytest_results_file: "junit/test-results.xml"
          pytest_cov_file: "coverage.xml"

      - name: Docs Check
        run: make docs-check
